print("Starting installation of osmium")
shell.run("wget https://raw.githubusercontent.com/knijn/osmium/main/os.lua os.lua")
shell.run("wget https://raw.githubusercontent.com/knijn/osmium/main/home.lua home.lua")
shell.run("wget https://raw.githubusercontent.com/knijn/osmium/main/startup.lua startup.lua")
print("Osmium succesfully installed")
print("Rebooting")
sleep(2)
os.reboot()
